version: '3'

services:
  database:
    image: postgres:16.1
    environment:
      POSTGRES_DB: found_focus
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
